name: Actualizar IPTV

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar extractor
        run: python extract_rcn.py

      - name: Subir cambios
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add lista.m3u
          git commit -m "Actualizar stream"
          git push
